<div style="border:solid Chocolate 2px; padding: 40px">

<b>Привет, Александр!👋</b>

Меня зовут Зуева Юлия, можно просто Юля 😏 Я буду ревьюером твоего проекта. Предлагаю обращаться на "ты", но если это неудобно, пожалуйста, скажи об этом!
    
Моя основная цель - помочь тебе стать компетентным Data Scientist'ом: вместе преодолеть трудности и еще больше развить твои сильные навыки 💪 В твоей работе я оставила комментарии, которые должны в этом помочь. Для твоего удобства комментарии раскрашены разными цветами: 

<br/>

<div class="alert alert-success">
<h2> Комментарий ревьюера <a class="tocSkip"> </h2>

<b>Все отлично!👍:</b> В случае, если решение на отдельном шаге является полностью правильным, или если я посчитаю нужным тебя за что-то похвалить. На такие решения можно опираться в будущих проектах.
</div>

<br/>

<div class="alert alert-warning">
    <h2> Комментарий ревьюера <a class="tocSkip"> </h2>
    
<b>Некоторые замечания и рекомендации💡:</b> В случае, когда решение на отдельном шаге станет еще лучше, если внести небольшие коррективы. Ты можешь учесть эти комментарии при выполнении будущих заданий или доработать проект сейчас (однако это не обязательно).
</div>


<br/>
<div class="alert alert-block alert-danger">
<h2> Комментарий ревьюера <a class="tocSkip"></h2>

    
<b>На доработку🤔:</b>
 В случае, когда решение на отдельном шаге требует существенной переработки и внесения правок. Напоминаю, что проект не может быть принят с первого раза, если ревью содержит комментарии, рекомендующие доработать шаги.
</div>
    


Чтобы наша с тобой работа была еще эффективнее, ты точно так же можешь оставлять комментарии и задавать мне вопросы. Для таких случаев, пожалуйста, выбери собственное оформление комментариев, которое будет отличаться от моего, чтобы не создавалась путаница. По этой же причине попрошу тебя не удалять и не изменять мои комментарии. Все это позволит лучше ориентироваться в нашем с тобой диалоге, а повторную проверку (в случае ее необходимости) выполнять оперативнее 🚀

Не спеши расстраиваться, если что-то не удалось с первого раза. Вместе мы обязательно разберемся со всеми трудностями! 🤓

<div class='alert alert-info'>
    <b> Комментарий студента:
    Юлия, привет. </b>
        
<b>Спасибо за такой подробный и вообще достаточно объемный ответ, куда объемней моей писанины как-минимум:)), свои ответы на твои комментарии буду выделять синим.</b>

<div class="alert alert-success">
<b>Комментарий ревьюера:</b>
    
Класс! Давай посмотрим, что получилось :)

<h1>Содержание<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Загрузка-данных" data-toc-modified-id="Загрузка-данных-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Загрузка данных</a></span></li><li><span><a href="#Умножение-матриц" data-toc-modified-id="Умножение-матриц-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Умножение матриц</a></span></li><li><span><a href="#Алгоритм-преобразования" data-toc-modified-id="Алгоритм-преобразования-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>Алгоритм преобразования</a></span></li><li><span><a href="#Проверка-алгоритма" data-toc-modified-id="Проверка-алгоритма-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>Проверка алгоритма</a></span><ul class="toc-item"><li><span><a href="#Бинго!-Качество-предсказаний-практически-идентичное,-ЧТД,-как-говорится." data-toc-modified-id="Бинго!-Качество-предсказаний-практически-идентичное,-ЧТД,-как-говорится.-4.1"><span class="toc-item-num">4.1&nbsp;&nbsp;</span><strong>Бинго! Качество предсказаний практически идентичное, ЧТД, как говорится.</strong></a></span></li></ul></li><li><span><a href="#Чек-лист-проверки" data-toc-modified-id="Чек-лист-проверки-5"><span class="toc-item-num">5&nbsp;&nbsp;</span>Чек-лист проверки</a></span></li></ul></div>

# Защита персональных данных клиентов

Вам нужно защитить данные клиентов страховой компании «Хоть потоп». Разработайте такой метод преобразования данных, чтобы по ним было сложно восстановить персональную информацию. Обоснуйте корректность его работы.

Нужно защитить данные, чтобы при преобразовании качество моделей машинного обучения не ухудшилось. Подбирать наилучшую модель не требуется.

## Загрузка данных

In [1]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score


df = pd.read_csv('/datasets/insurance.csv')
df.head()

Пол  Возраст  Зарплата  Члены семьи  Страховые выплаты
0    1     41.0   49600.0            1                  0
1    0     46.0   38000.0            1                  1
2    0     29.0   21000.0            0                  0
3    0     21.0   41700.0            2                  0
4    1     28.0   26100.0            0                  0

<div class="alert alert-success">
<h2> Комментарий ревьюера <a class="tocSkip"> </h2>

<b>Отличная работа!👍:</b> 

Класс! С данными познакомились, можем двигаться дальше :)

## Умножение матриц

Формула предсказания модели:

$$
a = Xw
$$

Формула для нахождения вектора весов:
$$
w = (X^T X)^{-1} X^T y
$$


Обозначения:

- $X$ — матрица признаков (нулевой столбец состоит из единиц)

- $R$ - рандомная обратимая матрица

- $y$ — вектор целевого признака

- $P$ — обратимая квадратная матрица, на которую умножаются признаки

- $w$ — вектор весов линейной регрессии (нулевой элемент равен сдвигу)

Предсказания модели домноженные на обратимую матрицу:
$${a}' = XR{w}'$$

Вектор весов домноженный на обратимую матрицу:
$$
{w}' = ((XR)^T (XR))^{-1} (XR)^T y = $$

$$(R^TX^TXR)^{-1} R^TX^T y = $$

$$R^{-1}(X^TX)^{-1}(R^T)^{-1} R^TX^T y =$$

(R^T)^{-1} и R^T сокращаются,так как являются обратными друг другу

$$R^{-1}(X^TX)^{-1} X^T y$$

*Подставляем полученный вектор весов в формулу предсказания модели помноженную на обратимую матрицу:*

$${a}' = XR{w}'= $$

$$XRR^{-1}(X^TX)^{-1} X^T y = $$

$$X(X^TX)^{-1} X^T y$$

Итого: 

$$a = {a}'$$


**Ответ:** Результаты преобразований показали, что качество предсказания модели после умножения на обратимую матрицу не изменится.

<div class="alert alert-block alert-danger">
<h2> Комментарий ревьюера <a class="tocSkip"></h2>

<b>На доработку🤔:</b>
    
Направление твоего доказательства верное! Но есть пара важных моментов, которые следует поправить. Ты не совсем корректно использовал свойство транспонирования произведения матриц. На самом деле оно выглядит так (обрати внимание, что порядок матриц меняется):     
$$
(AB)^T=B^T A^T
$$
    
Почему мы так заостряем внимание на порядке? Если при умножении обычных чисел нам не важно, умножаем ли мы 2 на 3 или 3 на 2, в результате все равно получим 6, то это становится важно при перемножении матриц. Чтобы произведение между двумя матрицами в принципе возможно было найти, должно выполняться условие: количество столбцов левой матрицы должно быть равно количеству строк правой. Если это условие выполнится, то в результате перемножения мы получим матрицу с количеством строк как у левой матрицы и количеством столбцов как у правой: $A_{2\times 3}B_{3\times 4} = C_{2\times 4}$. (заметь, что в примере умножить $B$ на $A$ уже не получится) 
    
Посмотрим на другой пример: $A_{2\times 3}B_{3\times 2} = C_{2\times 2}$ и $B_{3\times 2}A_{2\times 3} = D_{3\times 3}$. Как видишь, теперь у нас размерности соблюдаются и после перестановки, но обрати внимание, что из-за этого на выходе мы получаем совершенно разные матрицы. Поэтому произвольно менять местами матрицы в формуле недопустимо, так как это повлияет на результат вычислений.
    
С произведением двух матриц разобрались. Что если матриц больше? Как и в случае чисел, нам совершенно не важно, в каком порядке мы будем выполнять само умножение для получения результата. Допустим, нам нужно умножить 2 на 3 и на 4. Мы можем умножить сначала 2 на 3 и получить 6, а потом 6 умножить на 4 и получить 24. А можем сначала умножить 3 на 4, получить 12, а потом 2 умножить на 12 и получить те же самые 24. С матрицами точно так же (эта называется сочетательным свойством матриц или ассоциативностью): 
    $$A_{2\times 3}B_{3\times 4}C_{4\times 5} = (AB)_{2\times 4}C_{4\times 5} = A_{2\times 3}(BC)_{3\times 5} = D_{2\times 5}$$
    
Заметь, что даже при различном сочетании матриц для произведения мы сохраняеим их порядок, чтобы не нарушалось сочетание размерностей соседних матриц. Это достаточно важный момент в понимании линейной алгебры, поэтому хочу тебя попросить все-таки записать формулы с верной последовательностью перемножения матриц.
    
    
И еще одно небольшое замечание: у произведения $(X^TX)$ в некоторых строчках доказательства потерялась степень -1.

<div class='alert alert-info'>
    <b> Комментарий студента:</b>
    Отлично, все вопросы по поводу формульных преобразований вроде как я понял!
    Раскрытие скобок для произведений транспонированных матриц поправил, сбежавшую минус перввую степень поймал и вернул на место:)</div>

<div class="alert alert-success">
<h2> Комментарий ревьюера 2<a class="tocSkip"> </h2>

<b>Отличная работа!👍:</b> 

Теперь все супер :)

## Алгоритм преобразования

**Алгоритм такой**

- 1. Обучаем модель на исходном датасете
- 2. Предсказываем таргет на обучающих данных
- 3. Снимем метрику R2
- 4. Сгенерируем обратимую(определитель не равен нулю) матрицу при помощи np.random.sample() и проверим её на обратимость при помощи np.linalg.inv()
- 5. Умножим фичи на рандомную обратимую матрицу 
- 6. Снова предскажем таргет и снимем метрику
- 7. Сравниваем метрики и делаем выводы относительно нашей гипотезы


**Обоснование**
Не совсем понимаю, что тут ещё обосновывать 

<div class="alert alert-success">
<h2> Комментарий ревьюера <a class="tocSkip"> </h2>

<b>Отличная работа!👍:</b> 
    
Алгоритм верный! Можем переходить к реализации :) В обосновании можно просто сослаться на шаг с теоретическим доказательством.

## Проверка алгоритма

In [2]:
#Запишем фичи и таргет для сравнения в виде таблиц в переменные и выведем
features = df.drop(['Страховые выплаты'], axis=1)
target = df['Страховые выплаты']
print(features.head())
print(target.head())

   Пол  Возраст  Зарплата  Члены семьи
0    1     41.0   49600.0            1
1    0     46.0   38000.0            1
2    0     29.0   21000.0            0
3    0     21.0   41700.0            2
4    1     28.0   26100.0            0
0    0
1    1
2    0
3    0
4    0
Name: Страховые выплаты, dtype: int64


In [3]:
#Запишем фичи и таргет в виде массивов в переменные и выведем для ознакомления
features_X = np.array(df.drop(['Страховые выплаты'], axis=1))
target_y = np.array(df['Страховые выплаты'])
print(features_X)
print(target_y)

[[1.00e+00 4.10e+01 4.96e+04 1.00e+00]
 [0.00e+00 4.60e+01 3.80e+04 1.00e+00]
 [0.00e+00 2.90e+01 2.10e+04 0.00e+00]
 ...
 [0.00e+00 2.00e+01 3.39e+04 2.00e+00]
 [1.00e+00 2.20e+01 3.27e+04 3.00e+00]
 [1.00e+00 2.80e+01 4.06e+04 1.00e+00]]
[0 1 0 ... 0 0 0]


<div class="alert alert-block alert-danger">
<h2> Комментарий ревьюера <a class="tocSkip"></h2>

<b>На доработку🤔:</b>
    
Из-за того, что здесь возникла ошибка (функция head применима только к формату датафрейм, а мы перевели наши данные в массив), последующие ячейки с кодом не выполнились. Исправь, пожалуйста, к следующему разу.

<div class='alert alert-info'>
    <b> Комментарий студента:
    Отладил, вроде. А подскажи пожалуйста, есть ли аналогичные пандасовским head/tail методы в numpy? Или мы всегда грузим весь массив в память?  </b>

<div class="alert alert-success">
<b>Комментарий ревьюера:</b>
    
Ты можешь выводить определенные строки массива, обращаясь через индексы. Первые 10 строк: features_X[:10]. Последние 10 строк: features_X[-10:].

- **В виде массивов опознать данные уже непросто, пеперь посмотрим как данные будут выглядеть после умножения на обратимую матрицу и как изменится качество модели после преобразования фич**

In [4]:
#Создадим обратимую квадратную матрицу с количеством строк равным количеству столбцов в features_X и выведем для ознакомления
R = np.random.sample([features_X.shape[1],features_X.shape[1]])
display(R)
#Проверим получившуюся матрицу на обратимость
display(np.linalg.inv(R))

array([[0.31247074, 0.17264454, 0.54338992, 0.71936699],
       [0.95728321, 0.76956319, 0.26712956, 0.34332768],
       [0.7802452 , 0.59113204, 0.54602362, 0.64294199],
       [0.70219749, 0.63867554, 0.51706444, 0.70071765]])

array([[  5.22975735,   5.55432443,  -1.98732095,  -6.26691229],
       [ -6.73796437,  -4.96146026,   2.13784132,   7.38666687],
       [ -9.44914594, -10.19242698,  17.58889683,  -1.44408289],
       [  7.87316824,   6.47717698, -12.93600687,   2.04020912]])

- **Отлично, матрица обратима, можно преобразовывать фичи!**

In [5]:
#Домножим исходную матрицу с фичами на нашу новую обратимую матрицу
features_X_new = features_X.dot(R)
display(features_X_new)

array([[38740.42499489, 29352.51264407, 27094.78433543, 31905.41923725],
       [29694.05466818, 22499.05613991, 20761.7025973 , 24448.28942149],
       [16412.91032635, 12436.0901933 , 11474.24278448, 13511.73829857],
       ...,
       [26470.86219907, 20056.04480454, 18516.57744978, 21804.00145926],
       [25537.49719868, 19349.03680179, 17862.94381884, 21034.57781093],
       [31705.77355033, 24022.3199537 , 22177.09906805, 26114.47806491]])

<div class="alert alert-warning">
    <h2> Комментарий ревьюера <a class="tocSkip"> </h2>
    
<b>Некоторые замечания и рекомендации💡:</b> 

На будущее хочу предостеречь: в питоне есть несколько способов получить произведение двумерных матриц (numpy.dot(), numpy.multiply(), numpy.matmul(), через оператор @), но на матрицах большей размерности (трехмерные, четырехмерные и т.д.) результаты некоторых из них будут отличаться.

<div class='alert alert-info'>
    <b> Комментарий студента:</b>
    Так-так-так, а можно поподробнее с этого места? Мне, вообще, конечно же, по понятной причине всегда хочется скалярные произведения писать через "@", но тренажер в теории не принимал такой метод и требовал через A.dot(B) писать...А тут оказывается, что способов записи существенно больше чем два и они ещё в придачу отличаются по результату</div>

<div class="alert alert-success">
<b>Комментарий ревьюера:</b>
    
Отличаются по результату они только для матриц, которые имеют размерность больше, чем 2 (в этом проекте мы использовали только двумерные матрицы, поэтому ты мог использовать любую из функций). Я думаю, в чем заключается разница, лучше увидеть наглядно. Попробуй создать две трехмерные матрицы и перемножить их, используя, допустим, np.dot и @ (лучше задай их вручную через небольшие целые числа, чтобы можно было легко проследить, каким образом был получен результат, через какие действия). После этого изучи результаты, обращая особое внимание на размерности. Для того, чтобы возможно было перемножить через @, нужно, чтобы размерности матриц совпадали следующим образом: $A_{m,n,k}B_{m,k,p}$. Для того, чтобы возможно было перемножить через np.dot, нужно, чтобы размерности матриц совпадали следующим образом: $A_{m,n,k}B_{n,k,p}$. На практике, на самом деле, использование трехмерных и более многомерных матриц встречается не так часто. Предупредила тебя лишь на тот случай, если тебе когда-то придется с ними столкнуться. Ну а когда и что применять зависит от того, какую задачу ты решаешь. Здесь главное понимать, что ты получаешь на выходе, и соответствует ли это твоим представлениям о результате.

- **Вид даных, конечно, изменился до неузнаваемости, "сотрудники сбербанка" таким данным думаю нестрашны:)!**

Ну всё, в бой!!!!
Обучаем, прдсказываем, снимаем метрики до и после преобразования и сравниваем что получилось на выходе.

In [6]:
model_1 = LinearRegression()
model_1.fit(features_X, target_y)
predictions = model_1.predict(features_X)
print(r2_score(target_y, predictions))

0.4249455028666801


In [7]:
model_2 = LinearRegression()
model_2.fit(features_X_new, target_y)
predictions_2 = model_2.predict(features_X_new)
print(r2_score(target_y, predictions_2))

0.42494550286671506


### **Бинго! Качество предсказаний практически идентичное, ЧТД, как говорится.**

## Чек-лист проверки

Поставьте 'x' в выполненных пунктах. Далее нажмите Shift+Enter.

- [x]  Jupyter Notebook открыт
- [x]  Весь код выполняется без ошибок
- [x]  Ячейки с кодом расположены в порядке исполнения
- [x]  Выполнен шаг 1: данные загружены
- [x]  Выполнен шаг 2: получен ответ на вопрос об умножении матриц
    - [x]  Указан правильный вариант ответа
    - [x]  Вариант обоснован
- [x]  Выполнен шаг 3: предложен алгоритм преобразования
    - [x]  Алгоритм описан
    - [x]  Алгоритм обоснован
- [x]  Выполнен шаг 4: алгоритм проверен
    - [x]  Алгоритм реализован
    - [x]  Проведено сравнение качества моделей до и после преобразования

Из-за плохого(пока) пространственного мышления, не совмем доконца глубоко понял что проделал и что нам это дало. Если не сложно, объясни пожалуйста хотя бы схематично, почему, что и зачем мы здесь проделали:D. Так же не уверен, что правильно понял вот это преобразование ${w}' = ((XR)^T (XR))^{-1}$, а именно почему мы ABCD разложили как А (ВС) D.

<div class="alert alert-success">
<b>Комментарий ревьюера:</b> 

Насчет преобразования, выше тебе уже рассказала про сочетательное свойство матриц, оно дает нам возможность объединить матрицы таким образом. А используем мы его здесь, потому что нам нужно получить квадратные матрицы (иначе мы не сможем найти для них обратные): $R$ мы изначально задаем квадратной, значит при транспонировании она останется квадратной, а вот $X$ не является квадратной сама по себе, но при произведении с транспонированной версией мы как раз получаем квадратную матрицу, для которой возможно найти обратную.

Насчет того, что мы вообще проделали, и почему это работает. Давай для наглядности упростим все до двух признаков:
$$X = \begin{pmatrix}
x_{1,1} & x_{1,2}\\
x_{2,1} & x_{2,2}\\
x_{3,1} & x_{3,2}\\
\end{pmatrix}_{3\times 2} , R = \begin{pmatrix}
r_{1,1} & r_{1,2}\\
r_{2,1} & r_{2,2}\\
\end{pmatrix}_{2\times 2}$$
Теперь посмотрим, что будет получаться при перемножении (помним, что каждая строчка левой матрицы взаимодействует с каждым столбцом из правой матрицы, постарайся проследить по индексам):
$$XR = \begin{pmatrix}
(x_{11}r_{11} + x_{12}r_{21}) & (x_{11}r_{12} + x_{12}r_{22})\\
(x_{21}r_{11} + x_{22}r_{21}) & (x_{21}r_{12} + x_{22}r_{22})\\
(x_{31}r_{11} + x_{32}r_{21}) & (x_{31}r_{12} + x_{32}r_{22})\\
\end{pmatrix}_{3\times 2}$$
    
Каждый новый признак после шифрования превратился в линейную комбинацию всех наших изначальных признаков.
    
Теперь пока отвлечемся и разберем, что такое линейная регрессия. Каждая линейная регрессия имеет свое линейное уровнение. Для нашего случая в общем виде оно будет выглядеть так:
$$y = w_{0}*1 + w_{1}x_{1} + w_{2}x_{2},$$
где $y$ - это таргет, $x_{1}$ и $x_{2}$ наши признаки, а $w$ - соответствующие коэффициенты ($w_{0}$ - константа, чтобы ее ввести в уравнение, нужно при обучении к матрице добавить столбец из единиц как еще один признак). При обучении алгоритм проходится по всем нашим наблюдениям (то есть по всем сочетаниям $y$, $x_{1}$ и $x_{2}$ в данных) и пытается подобрать такие коэффициенты $w$, чтобы потом, когда бы мы подставляли $x_{1}$ и $x_{2}$ в формулу, мы могли бы получать предсказания, максимально близкие к настоящему $y$.
    

Теперь давай представим, что мы уже обучили линейные регрессии для обоих случаев (до и после шифрования) и получили два вектора коэффициентов: $w$ и $w'$. Подставим все в уравнение регрессии и получим, что для ситуации до шифрования предсказания будут равны:
$$\begin{pmatrix}y_{1}\\y_{2}\\y_{3}\end{pmatrix}_{3\times 1} = 
   \begin{pmatrix}w_{0}\\w_{0}\\w_{0}\end{pmatrix}_{3\times 1}+
   \begin{pmatrix}w_{1}x_{11}+ w_{2}x_{12}\\
w_{1}x_{21}+ w_{2}x_{22}\\
w_{1}x_{31}+ w_{2}x_{32}\end{pmatrix}_{3\times 1}$$
А после шифрования:
$$\begin{pmatrix}y'_{1}\\y'_{2}\\y'_{3}\end{pmatrix}_{3\times 1} = 
   \begin{pmatrix}w'_{0}\\w'_{0}\\w'_{0}\end{pmatrix}_{3\times 1}+
   \begin{pmatrix}w'_{1}(x_{11}r_{11} + x_{12}r_{21}) + w'_{2}(x_{11}r_{12} + x_{12}r_{22})\\
w'_{1}(x_{21}r_{11} + x_{22}r_{21}) + w'_{2} (x_{21}r_{12} + x_{22}r_{22})\\
w'_{1}(x_{31}r_{11} + x_{32}r_{21}) +w'_{2} (x_{31}r_{12} + x_{32}r_{22})\end{pmatrix}_{3\times 1} = 
\begin{pmatrix}w'_{0}\\w'_{0}\\w'_{0}\end{pmatrix}_{3\times 1}+
   \begin{pmatrix}(w'_{1}r_{11} + w'_{2}r_{12})x_{11} + (w'_{1}r_{21} + w'_{2}r_{22})x_{12}\\
(w'_{1}r_{11} + w'_{2}r_{12})x_{21} + (w'_{1}r_{21} + w'_{2}r_{22})x_{22}\\
(w'_{1}r_{11} + w'_{2}r_{12})x_{31} + (w'_{1}r_{21} + w'_{2}r_{22})x_{32}\end{pmatrix}_{3\times 1}
$$
   
    
То есть наши предсказания не изменились, так как 
    $$w_{0} = w'_{0}$$
    $$w_{1} = w'_{1}r_{11} + w'_{2}r_{12}$$ 
    $$w_{2} = w'_{1}r_{21} + w'_{2}r_{22}$$.

<div class="alert alert-success">
<b>Комментарий ревьюера:</b> 
    
По поводу константы: мы можем рассматривать ее как еще один дополнительный признак, ни одна формула, ни доказательство в целом от этого не поменяются, так как они универсальны и подойдут хоть для 100 признаков, хоть для миллиона :) Что вообще такое константа в модели? Уравнение линейной регрессии с константой выглядит следующим образом: $$y = w_{0}*1 + w_{1}*пол + w_{2}*возраст + w_{3}*зарплата + w_{4}*семья$$
После того, как мы обучим модель, получим значения всех коэффициентов $w$ и подстваим их в формулу выше, мы получим выражение, по которому сможем вычислять предсказание для каждого наблюдения (знаем пол, возраст, заплату, семью, подставляем значения, получаем предсказание). Все коэффициенты $w$ мы можем рассмтривать как оценку влияния соответствующего признака на целевую переменную. $w_{0}$ - это константа, этому числу в среднем будет равен таргет, если все остальные признаки будут равны 0 (то есть не будут оказывать влияния): 
$$y = w_{0}*1 + w_{1}*0 + w_{2}*0 + w_{3}*0 + w_{4}*0 = w_{0}$$
    
Теперь давай посмотрим, если относительно этого нулевого случая у нас будет меняться возраст:
$$y = w_{0}*1 + w_{1}*0 + w_{2}*1 + w_{3}*0 + w_{4}*0 = w_{0}+w_{2}$$
$$y = w_{0}*1 + w_{1}*0 + w_{2}*2 + w_{3}*0 + w_{4}*0 = w_{0}+w_{2}*2$$
Получается, если возраст будет меняться на единицу, то предсказание будет изменяться на $w_{2}$ от среднего значения (то есть от $w_{0}$). С остальными признакими точно так же, то есть значения коэффициентов $w$ говорят о том, как изменяется предсказание, если значение признака изменяется на 1.
    
На практике ты можешь добавлять константу (дополнительный столбец из 1 в матрицу) как до шифрования (тогда матрица $R$ 5 на 5, так как у нас 4 признака + 1 константа), так и после шифрования (тогда матрица $R$ 4 на 4, так как у нас 4 признака, константы при шифровании нет). Результат от этого не изменится (главное только соблюдать размерности). Почему так?
    
Я, наверное, не стану приводить тебе доказательство через формулы, чтобы не запутать еще больше. Покажу на одном примере, что разницы между этими двумя способами не будет. Будем рассматривать случай, когда мы шифруем вместе с константой (первый признак - константа, признаки 2 - 5 это наши оригинальные признаки: пол, возраст, зарплата, семья). То есть всего у нас 5 столбцов в матрице, и нам нужна матрица $R$ 5 на 5:
    $$ R = \begin{pmatrix}
r_{1,1} & r_{1,2} & r_{1,3} & r_{1,4} & r_{1,5}\\
r_{2,1} & r_{2,2} & r_{3,3} & r_{4,4} & r_{5,5}\\
r_{3,1} & r_{3,2} & r_{3,3} & r_{3,4} & r_{3,5}\\
r_{4,1} & r_{4,2} & r_{4,3} & r_{4,4} & r_{4,5}\\
r_{5,1} & r_{5,2} & r_{5,3} & r_{5,4} & r_{5,5}\\
\end{pmatrix}$$
    
После шифрования мы получим 5 новых признаков, которые являются линейной комбинацией признаков из изначальной матрицы (каждая строка изначальной матрицы взаимодействует с каждым столбцом из матрицы-ключа).
$$признак_{1} = r_{1,1}*1 + r_{2,1}*пол + r_{3,1}*возраст + r_{4,1}*зарплата + r_{5,1}*семья$$
$$признак_{2} = r_{1,2}*1 + r_{2,2}*пол + r_{3,2}*возраст + r_{4,2}*зарплата + r_{5,2}*семья...$$
и так далее для всех 5 новых признаков. То есть, получается, что каждый новый признак определяется конкретным столбцом из случайной матрицы (обрати внимание на индексы). И как мы уже знаем, качество после шифрования останется прежним.
    
    
А теперь давай представим ситуацию, что у нас случайно в матрице 5 на 5 в некоторых местах выпали 0 и 1, то есть наша матрица стала выглядеть так ($r$ - это любые другие числа):
$$ R = \begin{pmatrix}
1 & 0 & 0 & 0 & 0\\
0 & r_{2,2} & r_{3,3} & r_{4,4} & r_{5,5}\\
0 & r_{3,2} & r_{3,3} & r_{3,4} & r_{3,5}\\
0 & r_{4,2} & r_{4,3} & r_{4,4} & r_{4,5}\\
0 & r_{5,2} & r_{5,3} & r_{5,4} & r_{5,5}\\
\end{pmatrix}$$
    
После шифрования с помощью такой матрицы у нас зашифрованные признаки приняли следующий вид:
$$признак_{1} = 1*1 + 0*пол + 0*возраст + 0*зарплата + 0*семья = 1$$
$$признак_{2} = 0*1 + r_{2,2}*пол + r_{3,2}*возраст + r_{4,2}*зарплата + r_{5,2}*семья$$
$$признак_{3} = 0*1 + r_{2,3}*пол + r_{3,3}*возраст + r_{4,3}*зарплата + r_{5,3}*семья...$$
и так далее для всех 5 новых признаков. Получается, что в зашифрованной матрице константа так и осталась равна 1, а изменились только остальные 4 признака. Поскольку это частный случай ситуации, описанной выше, мы так же можем быть уверены, что качество моделей не поменяется. Но ведь к аналогичной ситуации мы могли бы прийти, если бы сначала зашифровали 4 признака с помощью матрицы 4 на 4:
$$ R = \begin{pmatrix}
r_{2,2} & r_{3,3} & r_{4,4} & r_{5,5}\\
r_{3,2} & r_{3,3} & r_{3,4} & r_{3,5}\\
r_{4,2} & r_{4,3} & r_{4,4} & r_{4,5}\\
r_{5,2} & r_{5,3} & r_{5,4} & r_{5,5}\\
\end{pmatrix}$$
а потом к ней бы уже добавили столбец из единиц. Получили бы на выходе ту же самую матрицу с новыми признаками. Раз в случае, описанном выше, качество модели не поменялось, получается, что оно не изменится и здесь. Вывод: нам не важно, в какой момент добавлять константу, качество все так же останется прежним. Главное соблюдать размерности, иначе у нас не получится перемножить матрицы.

<div class='alert alert-info'>
<b> Комментарий студента:</b>
<b>С константой так и не понял ничего:</b>
    
<b>Из теории:</b>
    
<b>У линейной регрессии признаки — это вектор чисел в n-мерном пространстве (допустим, x). Предсказание модели (a) вычисляется так: скалярно умножается вектор признаков на вектор весов (w; от англ. weights), затем к этому произведению прибавляется величина сдвига предсказания (англ. bias):</b>
<b>Вектор w и скаляр w0 — это параметры модели. В векторе w параметров n, а в w0 — один. То есть количество параметров больше длины вектора признаков на единицу.
Если длина вектора признаков равна единице, то в выборке всего один признак. Изобразим этот признак с ответами на графике:</b>
    
    А где тут, константа?

<div class="alert alert-success">
<b>Комментарий ревьюера 2:</b>
    
Здесь константа - это $w_{0}$. В уравнении линейной регрессии у нас есть коэффициенты для каждого из признаков, которые показывают, как соответствующий признак влияет на целевую переменную (какой вклад вносит каждый из признаков), плюс константа, которая показывает, чему равна целевая переменная, если ни один признак не оказывает влияние. Так и получается, что количество коэффициентов = количество признаков + 1 (константа). Получить значение константы возможно только через введение дополнительного "признака" из единиц (это чисто вспомогательный столбец, не несущий в себе никакой информации). Так как это все-таки теперь находится среди остальных признаков в матрице, расчет коэффициента-константы производится по аналогии со всеми остальными настоящими признаками (через формулу, которую мы использовали в доказательстве, только матрица Х имеет доп столбец). Но благодаря тому, что все значения в этом столбце равны 1 (а при умножении на 1 число не изменяется), получается, что мы для всех наблюдений получаем одинаковый вклад от константы (поэтому она и именуется константой). Но поскольку мы расчет константы проводили совместно с поиском остальных коэффициетов, у нас значение константы будет входить в вектор всех признаков. Возможно, эта ссылка поможет тебе разобраться чуть лучше: https://habr.com/ru/post/479398/. Кроме этого, рекомендую тебе попрактиковаться в перемножении матриц вручную на листочке, сначала на обычных числах, потом замени числа на буквы. Думаю, тогда придет окончательное осознание :)

<div class="alert alert-success">
<b>Комментарий ревьюера:</b> 
    
Надеюсь, объяснение можно будет понять, а то оно немного франкенштейн :) Собрала его из своих старых объяснений. Если что-то останется непонятным, или увидишь какие-то несостыковки, пиши!

<div style="border:solid Chocolate 2px; padding: 40px">

**Общий вывод по проекту**

Александр, спасибо за твой проект! У тебя замечательная работа! Очень аккуратная, снабженная пояснениями и выводами. Проверять - одно удовольствие! Осталось только доработать доказательство и код, чтобы все ячейки выполнялись, тогда все будет на высоте :) Если у тебя есть вопросы, или появится желание разобраться в чем-то подробнее, смело обращайся!

**Желаю удачи и жду твой проект на повторное ревью!** 😉
    
<img src="https://c.tenor.com/D4geDkAW9jgAAAAj/cat-paw.gif" width="100" height="50"/>